# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  grafana: grafana/k6@1.1.3
workflows:
  load_test:
    jobs:
     - grafana/k6:
          script: src/tech_radar/metrics.js